### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pascal-chenevas** [pascal-chenevas/carbone_cli_rs#1]
- [x] rename app.r/s to carbons.r/s

- [x] change option --json-data name 
- [x] fix help message (as a template can be also be downloaded)

 -o, --output <FILE>
          output file for the generated report

- [x] replace usage of const value like true/false by enums
